### ISSUE TITLE
think you got the wrong package

### ISSUE THREAD

**Issue by jimmywarting** [Marto130/challenge-improvein#1]
...Actually believe you meant to install standard and not standardjs

https://github.com/Marto130/challenge-improvein/blob/3fcb0b08f85fe87c8068fe6c0a767d610a68f250/package.json#L23

**Comment by Marto130** [comment]
You are right!! 
![image](https://user-images.githubusercontent.com/66214954/125172242-ef389300-e18e-11eb-95b5-a740ef61dcad.png)

**Comment by jimmywarting** [comment]
watch out for bad packages with similar names, it might do something hacky in the feature

**Comment by Marto130** [comment]
Fixed. Thankss !
